export type DesignArchetype =
  | 'swiss'
  | 'neo-brutalism'
  | 'organic-terracotta'
  | 'cyber-terminal'
  | 'oxford-heritage';

export interface ThemeConfig {
  id: string;
  name: string;
  category: 'heritage' | 'modern' | 'cyber' | 'artistic' | 'minimal';
  archetype: DesignArchetype;
  visualMood: string;
  headingFont: string;
  bodyFont: string;
  radius: string;
  borderStyle: string;
  light: {
    background: string;
    surface: string;
    foreground: string;
    primary: string;
    primaryForeground: string;
    accent: string;
    accentForeground: string;
    muted: string;
    mutedForeground: string;
    border: string;
    ring: string;
  };
  dark: {
    background: string;
    surface: string;
    foreground: string;
    primary: string;
    primaryForeground: string;
    accent: string;
    accentForeground: string;
    muted: string;
    mutedForeground: string;
    border: string;
    ring: string;
  };
}

export const THEMES: ThemeConfig[] = [
  {
    id: 'neo-brutalism',
    name: 'Neo-Brutalism Pop Velocity',
    category: 'artistic',
    archetype: 'neo-brutalism',
    visualMood: 'High-contrast graphic punch, 90s comic pop-art enthusiasm, hard offset shadows',
    headingFont: '"Clash Display", "Space Grotesk", sans-serif',
    bodyFont: '"Plus Jakarta Sans", sans-serif',
    radius: '0.5rem',
    borderStyle: '2.5px solid',
    light: {
      background: '#FEF08A',
      surface: '#FFFFFF',
      foreground: '#000000',
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      accent: '#F43F5E',
      accentForeground: '#FFFFFF',
      muted: '#FDE047',
      mutedForeground: '#000000',
      border: '#000000',
      ring: '#7C3AED',
    },
    dark: {
      background: '#18181B',
      surface: '#27272A',
      foreground: '#FFFFFF',
      primary: '#A78BFA',
      primaryForeground: '#000000',
      accent: '#FB7185',
      accentForeground: '#000000',
      muted: '#3F3F46',
      mutedForeground: '#E4E4E7',
      border: '#000000',
      ring: '#A78BFA',
    },
  },
  {
    id: 'swiss-international',
    name: 'Swiss Minimalist Grid',
    category: 'minimal',
    archetype: 'swiss',
    visualMood: 'Josef Müller-Brockmann precision, zero border-radius, hairline borders, objective modernism',
    headingFont: '"Neue Haas Grotesk", Inter, sans-serif',
    bodyFont: '"Roboto Mono", monospace',
    radius: '0px',
    borderStyle: '0.5px solid',
    light: {
      background: '#FFFFFF',
      surface: '#F8F9FA',
      foreground: '#000000',
      primary: '#000000',
      primaryForeground: '#FFFFFF',
      accent: '#E11D48',
      accentForeground: '#FFFFFF',
      muted: '#E9ECEF',
      mutedForeground: '#495057',
      border: '#000000',
      ring: '#000000',
    },
    dark: {
      background: '#0A0A0A',
      surface: '#141414',
      foreground: '#FFFFFF',
      primary: '#FFFFFF',
      primaryForeground: '#000000',
      accent: '#F43F5E',
      accentForeground: '#FFFFFF',
      muted: '#1F1F1F',
      mutedForeground: '#A3A3A3',
      border: '#2E2E2E',
      ring: '#FFFFFF',
    },
  },
  {
    id: 'terracotta-clay',
    name: 'Organic Terracotta & Mediterranean Clay',
    category: 'heritage',
    archetype: 'organic-terracotta',
    visualMood: 'Sun-baked pottery, humanist artisan warmth, generous contours, diffuse shadows',
    headingFont: 'Fraunces, serif',
    bodyFont: '"DM Sans", sans-serif',
    radius: '1.5rem',
    borderStyle: '1px solid',
    light: {
      background: '#FFF7ED',
      surface: '#FFFFFF',
      foreground: '#431407',
      primary: '#C86D51',
      primaryForeground: '#FFFFFF',
      accent: '#8A9A86',
      accentForeground: '#FFFFFF',
      muted: '#FFEDD5',
      mutedForeground: '#9A3412',
      border: '#FED7AA',
      ring: '#C86D51',
    },
    dark: {
      background: '#1C120C',
      surface: '#2D1A10',
      foreground: '#FFEDD5',
      primary: '#FB923C',
      primaryForeground: '#1C120C',
      accent: '#A3E635',
      accentForeground: '#1C120C',
      muted: '#3A2013',
      mutedForeground: '#FDBA74',
      border: '#431407',
      ring: '#FB923C',
    },
  },
  {
    id: 'oxford-heritage',
    name: 'Oxford Academic Heritage',
    category: 'heritage',
    archetype: 'oxford-heritage',
    visualMood: 'Scholarly authority, archival prestige, timeless bibliotheca',
    headingFont: 'Newsreader, serif',
    bodyFont: 'Inter, sans-serif',
    radius: '0.375rem',
    borderStyle: '1px solid',
    light: {
      background: '#FDFBF7',
      surface: '#FFFFFF',
      foreground: '#0A192F',
      primary: '#1E3A8A',
      primaryForeground: '#FFFFFF',
      accent: '#D97706',
      accentForeground: '#FFFFFF',
      muted: '#F3EFE6',
      mutedForeground: '#64748B',
      border: '#E2D9C8',
      ring: '#1E3A8A',
    },
    dark: {
      background: '#060D1A',
      surface: '#0C192E',
      foreground: '#F1F5F9',
      primary: '#3B82F6',
      primaryForeground: '#060D1A',
      accent: '#F59E0B',
      accentForeground: '#060D1A',
      muted: '#112240',
      mutedForeground: '#94A3B8',
      border: '#1E293B',
      ring: '#3B82F6',
    },
  },
  {
    id: 'cyber-monolith',
    name: 'Cybernetic Monolith HUD',
    category: 'cyber',
    archetype: 'cyber-terminal',
    visualMood: 'Neural interface, high-velocity developer terminal, obsidian cyan glow',
    headingFont: '"Space Grotesk", sans-serif',
    bodyFont: '"JetBrains Mono", monospace',
    radius: '0.125rem',
    borderStyle: '1px solid',
    light: {
      background: '#E2E8F0',
      surface: '#FFFFFF',
      foreground: '#020617',
      primary: '#0284C7',
      primaryForeground: '#FFFFFF',
      accent: '#059669',
      accentForeground: '#FFFFFF',
      muted: '#F1F5F9',
      mutedForeground: '#64748B',
      border: '#CBD5E1',
      ring: '#0284C7',
    },
    dark: {
      background: '#030712',
      surface: '#090D16',
      foreground: '#F8FAFC',
      primary: '#06B6D4',
      primaryForeground: '#030712',
      accent: '#10B981',
      accentForeground: '#030712',
      muted: '#0F172A',
      mutedForeground: '#64748B',
      border: '#1E293B',
      ring: '#06B6D4',
    },
  },
  {
    id: 'kyoto-zen',
    name: 'Kyoto Zen Minimalist',
    category: 'minimal',
    archetype: 'swiss',
    visualMood: 'Wabi-sabi calm, raw linen tactile serenity, distraction-free focus',
    headingFont: '"Shippori Mincho", "Noto Serif", serif',
    bodyFont: '"Plus Jakarta Sans", sans-serif',
    radius: '0.75rem',
    borderStyle: '0.5px solid',
    light: {
      background: '#F9F8F6',
      surface: '#FFFFFF',
      foreground: '#1C1917',
      primary: '#292524',
      primaryForeground: '#F5F5F4',
      accent: '#DC2626',
      accentForeground: '#FFFFFF',
      muted: '#F5F5F4',
      mutedForeground: '#78716C',
      border: '#E7E5E4',
      ring: '#292524',
    },
    dark: {
      background: '#121212',
      surface: '#1C1917',
      foreground: '#F5F5F4',
      primary: '#A8A29E',
      primaryForeground: '#121212',
      accent: '#EF4444',
      accentForeground: '#FFFFFF',
      muted: '#292524',
      mutedForeground: '#A8A29E',
      border: '#292524',
      ring: '#A8A29E',
    },
  },
  {
    id: 'nordic-aurora',
    name: 'Nordic Aurora Glass',
    category: 'artistic',
    archetype: 'organic-terracotta',
    visualMood: 'Sub-zero crystalline clarity, polar auroral luminescence, frosted glass',
    headingFont: '"Cabinet Grotesk", sans-serif',
    bodyFont: 'Switzer, sans-serif',
    radius: '1.25rem',
    borderStyle: '1px solid',
    light: {
      background: '#F0FDF4',
      surface: 'rgba(255,255,255,0.85)',
      foreground: '#0F172A',
      primary: '#059669',
      primaryForeground: '#FFFFFF',
      accent: '#6366F1',
      accentForeground: '#FFFFFF',
      muted: '#DCFCE7',
      mutedForeground: '#475569',
      border: 'rgba(5,150,105,0.15)',
      ring: '#059669',
    },
    dark: {
      background: '#041014',
      surface: 'rgba(9,27,33,0.8)',
      foreground: '#ECFDF5',
      primary: '#34D399',
      primaryForeground: '#041014',
      accent: '#818CF8',
      accentForeground: '#041014',
      muted: '#06282D',
      mutedForeground: '#6EE7B7',
      border: 'rgba(52,211,153,0.2)',
      ring: '#34D399',
    },
  },
  {
    id: 'bauhaus-modern',
    name: 'Bauhaus Constructivist Modern',
    category: 'artistic',
    archetype: 'neo-brutalism',
    visualMood: 'De Stijl primary colors, geometric balance, constructivist dynamism',
    headingFont: 'Syne, sans-serif',
    bodyFont: '"Instrument Sans", sans-serif',
    radius: '0.25rem',
    borderStyle: '2px solid',
    light: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      foreground: '#0F172A',
      primary: '#1D4ED8',
      primaryForeground: '#FFFFFF',
      accent: '#EAB308',
      accentForeground: '#000000',
      muted: '#E2E8F0',
      mutedForeground: '#475569',
      border: '#1E293B',
      ring: '#1D4ED8',
    },
    dark: {
      background: '#0B1120',
      surface: '#1E293B',
      foreground: '#F1F5F9',
      primary: '#3B82F6',
      primaryForeground: '#0B1120',
      accent: '#FACC15',
      accentForeground: '#000000',
      muted: '#0F172A',
      mutedForeground: '#94A3B8',
      border: '#334155',
      ring: '#3B82F6',
    },
  },
  {
    id: 'tokyo-arcade',
    name: 'Tokyo Midnight Neon Arcade',
    category: 'cyber',
    archetype: 'cyber-terminal',
    visualMood: 'Shibuya neon alleys, synthwave pulse, retro-futuristic arcade gamification',
    headingFont: 'Sora, sans-serif',
    bodyFont: '"Fira Code", monospace',
    radius: '0.625rem',
    borderStyle: '1px solid',
    light: {
      background: '#EEF2FF',
      surface: '#FFFFFF',
      foreground: '#1E1B4B',
      primary: '#4F46E5',
      primaryForeground: '#FFFFFF',
      accent: '#D946EF',
      accentForeground: '#FFFFFF',
      muted: '#E0E7FF',
      mutedForeground: '#4338CA',
      border: '#C7D2FE',
      ring: '#4F46E5',
    },
    dark: {
      background: '#090514',
      surface: '#140A28',
      foreground: '#FAF5FF',
      primary: '#A855F7',
      primaryForeground: '#090514',
      accent: '#EC4899',
      accentForeground: '#090514',
      muted: '#1E0D3A',
      mutedForeground: '#C084FC',
      border: '#2E1065',
      ring: '#A855F7',
    },
  },
  {
    id: 'obsidian-carbon',
    name: 'Obsidian Slate & Carbon',
    category: 'modern',
    archetype: 'swiss',
    visualMood: 'Precision engineering, executive dark mode, ultra-high information density',
    headingFont: '"Geist Sans", sans-serif',
    bodyFont: '"Geist Mono", monospace',
    radius: '0.5rem',
    borderStyle: '1px solid',
    light: {
      background: '#F1F5F9',
      surface: '#FFFFFF',
      foreground: '#0F172A',
      primary: '#0F172A',
      primaryForeground: '#FFFFFF',
      accent: '#10B981',
      accentForeground: '#FFFFFF',
      muted: '#E2E8F0',
      mutedForeground: '#64748B',
      border: '#CBD5E1',
      ring: '#0F172A',
    },
    dark: {
      background: '#020408',
      surface: '#0B0F19',
      foreground: '#F8FAFC',
      primary: '#38BDF8',
      primaryForeground: '#020408',
      accent: '#2DD4BF',
      accentForeground: '#020408',
      muted: '#111827',
      mutedForeground: '#94A3B8',
      border: '#1E293B',
      ring: '#38BDF8',
    },
  },
  {
    id: 'botanical-forest',
    name: 'Botanical Herbarium',
    category: 'heritage',
    archetype: 'organic-terracotta',
    visualMood: 'Victorian botanical garden, pressed wildflower manuscripts, organic wellness',
    headingFont: '"Playfair Display", serif',
    bodyFont: 'Outfit, sans-serif',
    radius: '0.875rem',
    borderStyle: '1px solid',
    light: {
      background: '#FCFBF7',
      surface: '#FFFFFF',
      foreground: '#14532D',
      primary: '#15803D',
      primaryForeground: '#FFFFFF',
      accent: '#B45309',
      accentForeground: '#FFFFFF',
      muted: '#F0FDF4',
      mutedForeground: '#166534',
      border: '#DCFCE7',
      ring: '#15803D',
    },
    dark: {
      background: '#051B11',
      surface: '#0C2E1F',
      foreground: '#ECFDF5',
      primary: '#4ADE80',
      primaryForeground: '#051B11',
      accent: '#FBBF24',
      accentForeground: '#051B11',
      muted: '#133E2B',
      mutedForeground: '#86EFAC',
      border: '#14532D',
      ring: '#4ADE80',
    },
  },
  {
    id: 'linear-devstudio',
    name: 'Linear Dark Minimalist',
    category: 'modern',
    archetype: 'swiss',
    visualMood: 'Raycast / Linear polished simplicity, effortless keyboard-first navigation',
    headingFont: 'Geist, sans-serif',
    bodyFont: 'Inter, sans-serif',
    radius: '0.375rem',
    borderStyle: '0.5px solid',
    light: {
      background: '#FAFAFA',
      surface: '#FFFFFF',
      foreground: '#18181B',
      primary: '#6366F1',
      primaryForeground: '#FFFFFF',
      accent: '#3B82F6',
      accentForeground: '#FFFFFF',
      muted: '#F4F4F5',
      mutedForeground: '#71717A',
      border: '#E4E4E7',
      ring: '#6366F1',
    },
    dark: {
      background: '#09090B',
      surface: '#18181B',
      foreground: '#FAFAFA',
      primary: '#818CF8',
      primaryForeground: '#09090B',
      accent: '#60A5FA',
      accentForeground: '#09090B',
      muted: '#27272A',
      mutedForeground: '#A1A1AA',
      border: '#27272A',
      ring: '#818CF8',
    },
  },
  {
    id: 'rams-functionalism',
    name: '1970s Dieter Rams Braun',
    category: 'modern',
    archetype: 'neo-brutalism',
    visualMood: 'Tactile hardware knobs, warm analog industrial meters, functional honesty',
    headingFont: '"DM Sans", sans-serif',
    bodyFont: '"Work Sans", sans-serif',
    radius: '0.625rem',
    borderStyle: '1px solid',
    light: {
      background: '#F5F5F0',
      surface: '#FFFFFF',
      foreground: '#262626',
      primary: '#EA580C',
      primaryForeground: '#FFFFFF',
      accent: '#CA8A04',
      accentForeground: '#FFFFFF',
      muted: '#E7E5E4',
      mutedForeground: '#57534E',
      border: '#D4D4D8',
      ring: '#EA580C',
    },
    dark: {
      background: '#1C1917',
      surface: '#292524',
      foreground: '#F5F5F4',
      primary: '#F97316',
      primaryForeground: '#1C1917',
      accent: '#EAB308',
      accentForeground: '#1C1917',
      muted: '#34302D',
      mutedForeground: '#A8A29E',
      border: '#44403C',
      ring: '#F97316',
    },
  },
  {
    id: 'astral-nebula',
    name: 'Astral Nebula Deep Space',
    category: 'artistic',
    archetype: 'organic-terracotta',
    visualMood: 'Interstellar discovery, celestial purple luminescence, gravitational orbits',
    headingFont: '"Cabinet Grotesk", sans-serif',
    bodyFont: 'Satoshi, sans-serif',
    radius: '1.125rem',
    borderStyle: '1px solid',
    light: {
      background: '#FAF5FF',
      surface: '#FFFFFF',
      foreground: '#3B0764',
      primary: '#7E22CE',
      primaryForeground: '#FFFFFF',
      accent: '#0284C7',
      accentForeground: '#FFFFFF',
      muted: '#F3E8FF',
      mutedForeground: '#6B21A8',
      border: '#E9D5FF',
      ring: '#7E22CE',
    },
    dark: {
      background: '#030014',
      surface: '#0C0728',
      foreground: '#FAF5FF',
      primary: '#A855F7',
      primaryForeground: '#030014',
      accent: '#38BDF8',
      accentForeground: '#030014',
      muted: '#190E45',
      mutedForeground: '#D8B4FE',
      border: '#241442',
      ring: '#A855F7',
    },
  },
  {
    id: 'vogue-editorial',
    name: 'Vogue Haute Editorial',
    category: 'heritage',
    archetype: 'swiss',
    visualMood: 'High-fashion luxury publication, asymmetric editorial layouts, stark contrast',
    headingFont: '"Cormorant Garamond", serif',
    bodyFont: 'Manrope, sans-serif',
    radius: '0px',
    borderStyle: '1px solid',
    light: {
      background: '#FFFFFF',
      surface: '#FAF9F6',
      foreground: '#000000',
      primary: '#000000',
      primaryForeground: '#FFFFFF',
      accent: '#D4AF37',
      accentForeground: '#000000',
      muted: '#F4F3EF',
      mutedForeground: '#555555',
      border: '#E5E5E5',
      ring: '#000000',
    },
    dark: {
      background: '#050505',
      surface: '#0F0F0F',
      foreground: '#FFFFFF',
      primary: '#D4AF37',
      primaryForeground: '#050505',
      accent: '#F5F5F5',
      accentForeground: '#050505',
      muted: '#181818',
      mutedForeground: '#999999',
      border: '#222222',
      ring: '#D4AF37',
    },
  },
  {
    id: 'solarized-studio',
    name: 'Solarized High-Contrast Studio',
    category: 'modern',
    archetype: 'neo-brutalism',
    visualMood: 'Ethan Schoonover color theory, zero eye strain for 12-hour immersive study',
    headingFont: '"IBM Plex Sans", sans-serif',
    bodyFont: '"IBM Plex Mono", monospace',
    radius: '0.5rem',
    borderStyle: '1.5px solid',
    light: {
      background: '#FDF6E3',
      surface: '#EEE8D5',
      foreground: '#002B36',
      primary: '#268BD2',
      primaryForeground: '#FDF6E3',
      accent: '#B58900',
      accentForeground: '#FDF6E3',
      muted: '#E4DCB9',
      mutedForeground: '#586E75',
      border: '#93A1A1',
      ring: '#268BD2',
    },
    dark: {
      background: '#002B36',
      surface: '#073642',
      foreground: '#93A1A1',
      primary: '#2AA198',
      primaryForeground: '#002B36',
      accent: '#CB4B16',
      accentForeground: '#002B36',
      muted: '#0A4756',
      mutedForeground: '#839496',
      border: '#586E75',
      ring: '#2AA198',
    },
  },
  {
    id: 'pastel-claymorphism',
    name: 'Pastel Claymorphism 3D',
    category: 'artistic',
    archetype: 'organic-terracotta',
    visualMood: 'Playful pillowy soft clay, friendly gamified language learning',
    headingFont: '"Plus Jakarta Sans", sans-serif',
    bodyFont: 'Nunito, sans-serif',
    radius: '1.75rem',
    borderStyle: '2px solid',
    light: {
      background: '#FFFBEB',
      surface: '#FEF3C7',
      foreground: '#78350F',
      primary: '#F43F5E',
      primaryForeground: '#FFFFFF',
      accent: '#0EA5E9',
      accentForeground: '#FFFFFF',
      muted: '#FDE68A',
      mutedForeground: '#92400E',
      border: 'rgba(244,63,94,0.2)',
      ring: '#F43F5E',
    },
    dark: {
      background: '#1C1917',
      surface: '#292524',
      foreground: '#FEF3C7',
      primary: '#FB7185',
      primaryForeground: '#1C1917',
      accent: '#38BDF8',
      accentForeground: '#1C1917',
      muted: '#3E3834',
      mutedForeground: '#FCD34D',
      border: 'rgba(251,113,133,0.2)',
      ring: '#FB7185',
    },
  },
  {
    id: 'art-deco-noir',
    name: 'Art Deco Gilded Noir',
    category: 'heritage',
    archetype: 'oxford-heritage',
    visualMood: 'The Great Gatsby roaring twenties, brass filigree, noir luxury',
    headingFont: 'Marcellus, serif',
    bodyFont: 'Montserrat, sans-serif',
    radius: '0.25rem',
    borderStyle: '1px solid',
    light: {
      background: '#FDFEFE',
      surface: '#F4F6F6',
      foreground: '#17202A',
      primary: '#B7950B',
      primaryForeground: '#FFFFFF',
      accent: '#117A65',
      accentForeground: '#FFFFFF',
      muted: '#E5E8E8',
      mutedForeground: '#5D6D7E',
      border: '#D4AC0D',
      ring: '#B7950B',
    },
    dark: {
      background: '#0B0C10',
      surface: '#1F2833',
      foreground: '#C5C6C7',
      primary: '#D4AC0D',
      primaryForeground: '#0B0C10',
      accent: '#45A29E',
      accentForeground: '#0B0C10',
      muted: '#141E28',
      mutedForeground: '#8D99AE',
      border: '#66FCF1',
      ring: '#D4AC0D',
    },
  },
  {
    id: 'lavender-mist',
    name: 'Lavender Mist Wellness',
    category: 'minimal',
    archetype: 'organic-terracotta',
    visualMood: 'Stress-free cognitive load reduction, soothing lavender aromatherapy aesthetic',
    headingFont: 'Outfit, sans-serif',
    bodyFont: 'Figtree, sans-serif',
    radius: '1.375rem',
    borderStyle: '1px solid',
    light: {
      background: '#FAF5FF',
      surface: '#FFFFFF',
      foreground: '#334155',
      primary: '#8B5CF6',
      primaryForeground: '#FFFFFF',
      accent: '#06B6D4',
      accentForeground: '#FFFFFF',
      muted: '#F3E8FF',
      mutedForeground: '#6B21A8',
      border: '#E9D5FF',
      ring: '#8B5CF6',
    },
    dark: {
      background: '#1E1035',
      surface: '#2E1A4E',
      foreground: '#F3E8FF',
      primary: '#C084FC',
      primaryForeground: '#1E1035',
      accent: '#22D3EE',
      accentForeground: '#1E1035',
      muted: '#3D2466',
      mutedForeground: '#E9D5FF',
      border: '#4C1D95',
      ring: '#C084FC',
    },
  },
  {
    id: 'industrial-blueprint',
    name: 'Industrial Engineering Blueprint',
    category: 'cyber',
    archetype: 'swiss',
    visualMood: 'CAD drafting table, technical architectural diagrams, metric precision',
    headingFont: '"Space Mono", monospace',
    bodyFont: '"Overpass Mono", monospace',
    radius: '0.1875rem',
    borderStyle: '1px dashed',
    light: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      foreground: '#1E3A8A',
      primary: '#1E40AF',
      primaryForeground: '#FFFFFF',
      accent: '#CA8A04',
      accentForeground: '#FFFFFF',
      muted: '#EFF6FF',
      mutedForeground: '#3B82F6',
      border: '#93C5FD',
      ring: '#1E40AF',
    },
    dark: {
      background: '#0B192C',
      surface: '#1E3E62',
      foreground: '#E0E1DD',
      primary: '#60A5FA',
      primaryForeground: '#0B192C',
      accent: '#F59E0B',
      accentForeground: '#0B192C',
      muted: '#122B48',
      mutedForeground: '#93C5FD',
      border: '#1E40AF',
      ring: '#60A5FA',
    },
  },
  {
    id: 'mediterranean-linen',
    name: 'Mediterranean Coastal Linen',
    category: 'heritage',
    archetype: 'organic-terracotta',
    visualMood: 'Sun-drenched Aegean sea, crisp sea-salt linen, Santorini serenity',
    headingFont: '"Playfair Display", serif',
    bodyFont: 'Karla, sans-serif',
    radius: '0.75rem',
    borderStyle: '1px solid',
    light: {
      background: '#FBFBF9',
      surface: '#FFFFFF',
      foreground: '#0C4A6E',
      primary: '#0284C7',
      primaryForeground: '#FFFFFF',
      accent: '#EA580C',
      accentForeground: '#FFFFFF',
      muted: '#F0F9FF',
      mutedForeground: '#0369A1',
      border: '#BAE6FD',
      ring: '#0284C7',
    },
    dark: {
      background: '#082F49',
      surface: '#0C4A6E',
      foreground: '#F0F9FF',
      primary: '#38BDF8',
      primaryForeground: '#082F49',
      accent: '#FB923C',
      accentForeground: '#082F49',
      muted: '#0F567F',
      mutedForeground: '#BAE6FD',
      border: '#0369A1',
      ring: '#38BDF8',
    },
  },
  {
    id: 'vintage-risograph',
    name: 'Vintage Risograph Studio',
    category: 'artistic',
    archetype: 'neo-brutalism',
    visualMood: 'Hand-printed zine, fluorescent ink registration, authentic halftone texture',
    headingFont: '"Bricolage Grotesque", sans-serif',
    bodyFont: '"Public Sans", sans-serif',
    radius: '0.375rem',
    borderStyle: '2px solid',
    light: {
      background: '#FFFDF0',
      surface: '#FFFFFF',
      foreground: '#18181B',
      primary: '#E11D48',
      primaryForeground: '#FFFFFF',
      accent: '#0D9488',
      accentForeground: '#FFFFFF',
      muted: '#FEF2F2',
      mutedForeground: '#991B1B',
      border: '#18181B',
      ring: '#E11D48',
    },
    dark: {
      background: '#18181B',
      surface: '#27272A',
      foreground: '#FFFDF0',
      primary: '#F43F5E',
      primaryForeground: '#18181B',
      accent: '#2DD4BF',
      accentForeground: '#18181B',
      muted: '#3F3F46',
      mutedForeground: '#FDA4AF',
      border: '#3F3F46',
      ring: '#F43F5E',
    },
  },
  {
    id: 'quantum-frost',
    name: 'Prismatic Quantum Frost',
    category: 'cyber',
    archetype: 'cyber-terminal',
    visualMood: 'Optical dispersion, opalescent glass, futuristic holographic refraction',
    headingFont: '"General Sans", sans-serif',
    bodyFont: 'Epilogue, sans-serif',
    radius: '1rem',
    borderStyle: '1px solid',
    light: {
      background: '#FAFAFA',
      surface: '#FFFFFF',
      foreground: '#0F172A',
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      accent: '#06B6D4',
      accentForeground: '#FFFFFF',
      muted: '#F5F3FF',
      mutedForeground: '#6D28D9',
      border: '#E2E8F0',
      ring: '#7C3AED',
    },
    dark: {
      background: '#030712',
      surface: '#0B1120',
      foreground: '#F8FAFC',
      primary: '#A78BFA',
      primaryForeground: '#030712',
      accent: '#22D3EE',
      accentForeground: '#030712',
      muted: '#141A2D',
      mutedForeground: '#C4B5FD',
      border: '#1E293B',
      ring: '#A78BFA',
    },
  },
  {
    id: 'savile-row',
    name: 'Savile Row Bespoke Tailoring',
    category: 'heritage',
    archetype: 'oxford-heritage',
    visualMood: 'Sartorial craftsmanship, chalk stripe wool, polished horn button brass',
    headingFont: '"Bodoni Moda", serif',
    bodyFont: 'Supreme, sans-serif',
    radius: '0.25rem',
    borderStyle: '1px dotted',
    light: {
      background: '#F8F9FA',
      surface: '#FFFFFF',
      foreground: '#0A1128',
      primary: '#6B1D2F',
      primaryForeground: '#FFFFFF',
      accent: '#C59B27',
      accentForeground: '#0A1128',
      muted: '#F1F3F5',
      mutedForeground: '#495057',
      border: '#D1D5DB',
      ring: '#6B1D2F',
    },
    dark: {
      background: '#111318',
      surface: '#1B1E24',
      foreground: '#F3F4F6',
      primary: '#9E2A2B',
      primaryForeground: '#F3F4F6',
      accent: '#D4AF37',
      accentForeground: '#111318',
      muted: '#242831',
      mutedForeground: '#9CA3AF',
      border: '#2C3038',
      ring: '#9E2A2B',
    },
  },
  {
    id: 'solarpunk-biomimicry',
    name: 'Solarpunk Biomimicry Living Interface',
    category: 'artistic',
    archetype: 'organic-terracotta',
    visualMood: 'Clean ecological futurism, photosynthesis solar energy, botanical harmony',
    headingFont: '"Cabinet Grotesk", sans-serif',
    bodyFont: '"Albert Sans", sans-serif',
    radius: '1.25rem',
    borderStyle: '1px solid',
    light: {
      background: '#FEFCE8',
      surface: '#FFFFFF',
      foreground: '#14532D',
      primary: '#15803D',
      primaryForeground: '#FFFFFF',
      accent: '#D97706',
      accentForeground: '#FFFFFF',
      muted: '#FEF9C3',
      mutedForeground: '#166534',
      border: '#BBF7D0',
      ring: '#15803D',
    },
    dark: {
      background: '#052E16',
      surface: '#064E3B',
      foreground: '#F0FDF4',
      primary: '#86EFAC',
      primaryForeground: '#052E16',
      accent: '#FDE047',
      accentForeground: '#052E16',
      muted: '#093B2D',
      mutedForeground: '#BBF7D0',
      border: '#15803D',
      ring: '#86EFAC',
    },
  },
];

export const DEFAULT_THEME_ID = 'neo-brutalism';
