/**
 * Oxford 3000™ - Comprehensive Theme & Color Palette Engine
 * 3 Distinct Themes with 4 Tailored Color Variations Each (12 Total Palettes)
 */

export const THEME_DEFINITIONS = {
  brutalism: {
    id: 'brutalism',
    name: 'النيو-بروتاليزم (Neo-Brutalism)',
    emoji: '⚡',
    description: 'خطوط عريضة، ظلال بارزة، وألوان بوب حيوية عالية التباين',
    fontEn: 'Plus Jakarta Sans / Inter',
    fontAr: 'Cairo',
    palettes: [
      {
        id: 'classic-blue',
        name: 'أكسفورد الأزرق الملكي',
        accentLight: '#2563EB',
        accentDark: '#3B82F6',
        accentHover: '#1D4ED8',
        shadowColorLight: '#111827',
        shadowColorDark: '#3B82F6',
        previewColors: ['#2563EB', '#111827', '#FBBF24'],
      },
      {
        id: 'cyber-pink',
        name: 'نيون الوردي السايبر',
        accentLight: '#DB2777',
        accentDark: '#F472B6',
        accentHover: '#BE185D',
        shadowColorLight: '#111827',
        shadowColorDark: '#F472B6',
        previewColors: ['#DB2777', '#06B6D4', '#FACC15'],
      },
      {
        id: 'toxic-lime',
        name: 'أخضر ليموني متوهج',
        accentLight: '#65A30D',
        accentDark: '#84CC16',
        accentHover: '#4D7C0F',
        shadowColorLight: '#111827',
        shadowColorDark: '#84CC16',
        previewColors: ['#84CC16', '#2563EB', '#111827'],
      },
      {
        id: 'sunset-orange',
        name: 'برتقالي ناري كلاسيك',
        accentLight: '#EA580C',
        accentDark: '#FB923C',
        accentHover: '#C2410C',
        shadowColorLight: '#111827',
        shadowColorDark: '#FB923C',
        previewColors: ['#EA580C', '#8B5CF6', '#FBBF24'],
      },
    ],
  },

  organic: {
    id: 'organic',
    name: 'التيراكوتا الطبيعي (Organic Terracotta)',
    emoji: '🌿',
    description: 'ألوان ترابية طبيعية هادئة مع أسطح عاجية مريحة وحواف ناعمة',
    fontEn: 'Outfit / Tajawal',
    fontAr: 'Tajawal',
    palettes: [
      {
        id: 'terracotta-clay',
        name: 'طين التيراكوتا الكلاسيكي',
        accentLight: '#D96B43',
        accentDark: '#E07A5F',
        accentHover: '#C25A34',
        shadowColorLight: 'rgba(184, 115, 51, 0.25)',
        shadowColorDark: 'rgba(224, 122, 95, 0.35)',
        previewColors: ['#D96B43', '#F5EFE6', '#2D1A12'],
      },
      {
        id: 'sage-olive',
        name: 'أخضر الميرمية والزيتون',
        accentLight: '#4D7C0F',
        accentDark: '#65A30D',
        accentHover: '#3F6212',
        shadowColorLight: 'rgba(77, 124, 15, 0.25)',
        shadowColorDark: 'rgba(101, 163, 13, 0.35)',
        previewColors: ['#4D7C0F', '#F7F5F0', '#1F3316'],
      },
      {
        id: 'desert-sand',
        name: 'عنبر الرمال الذهبية',
        accentLight: '#C27803',
        accentDark: '#D97706',
        accentHover: '#A16207',
        shadowColorLight: 'rgba(194, 120, 3, 0.25)',
        shadowColorDark: 'rgba(217, 119, 6, 0.35)',
        previewColors: ['#D97706', '#FFFBEB', '#451A03'],
      },
      {
        id: 'dusty-rose',
        name: 'وردي رملي هادئ',
        accentLight: '#BE185D',
        accentDark: '#DB2777',
        accentHover: '#9D174D',
        shadowColorLight: 'rgba(190, 24, 93, 0.25)',
        shadowColorDark: 'rgba(219, 39, 119, 0.35)',
        previewColors: ['#DB2777', '#FFF1F2', '#4C0519'],
      },
    ],
  },

  swiss: {
    id: 'swiss',
    name: 'المينيمالي السويسري (Swiss Minimalist)',
    emoji: '🇨🇭',
    description: 'دقة هندسية، أبيض وأسود ناصع، ونبرات ألوان صريحة ومباشرة',
    fontEn: 'Inter',
    fontAr: 'Cairo',
    palettes: [
      {
        id: 'swiss-red',
        name: 'أحمر هيلفيتيكا السويسري',
        accentLight: '#DC2626',
        accentDark: '#EF4444',
        accentHover: '#B91C1C',
        shadowColorLight: 'rgba(220, 38, 38, 0.25)',
        shadowColorDark: 'rgba(239, 68, 68, 0.35)',
        previewColors: ['#DC2626', '#09090B', '#FFFFFF'],
      },
      {
        id: 'nordic-indigo',
        name: 'أزرق الإنديغو النورديك',
        accentLight: '#4338CA',
        accentDark: '#6366F1',
        accentHover: '#3730A3',
        shadowColorLight: 'rgba(67, 56, 202, 0.25)',
        shadowColorDark: 'rgba(99, 102, 241, 0.35)',
        previewColors: ['#4338CA', '#0F172A', '#F8FAFC'],
      },
      {
        id: 'pure-emerald',
        name: 'زمرد مينيمال ناصع',
        accentLight: '#059669',
        accentDark: '#10B981',
        accentHover: '#047857',
        shadowColorLight: 'rgba(5, 150, 105, 0.25)',
        shadowColorDark: 'rgba(16, 185, 129, 0.35)',
        previewColors: ['#059669', '#18181B', '#FAFAFA'],
      },
      {
        id: 'monochrome-black',
        name: 'مونوكروم كلاسيك (Mono)',
        accentLight: '#18181B',
        accentDark: '#F4F4F5',
        accentHover: '#27272A',
        shadowColorLight: 'rgba(0, 0, 0, 0.2)',
        shadowColorDark: 'rgba(255, 255, 255, 0.25)',
        previewColors: ['#18181B', '#71717A', '#F4F4F5'],
      },
    ],
  },
};

export const HIGH_CONTRAST_PRESETS = [
  {
    id: 'ultra-contrast-dark',
    name: 'تباين ليلي فائق (Ultra Dark)',
    emoji: '⚡',
    description: 'خط أبيض ناصع مع مربعات وبطاقات داكنة عميقة وحدود زرقاء واضحة',
    textColor: '#FFFFFF',
    textMuted: '#94A3B8',
    cardBg: '#111827',
    surfaceBg: '#1F2937',
    pageBg: '#090D16',
    accentColor: '#F59E0B',
    borderColor: '#374151',
    mode: 'dark',
  },
  {
    id: 'cyber-neon',
    name: 'سايبر نيون مضيء (Cyber Neon)',
    emoji: '🌌',
    description: 'ألوان نيون فسفورية عالية الإضاءة مع تباين قوي وسهل القراءة',
    textColor: '#E0F2FE',
    textMuted: '#7DD3FC',
    cardBg: '#0F172A',
    surfaceBg: '#1E293B',
    pageBg: '#020617',
    accentColor: '#06B6D4',
    borderColor: '#0284C7',
    mode: 'dark',
  },
  {
    id: 'amoled-pure-black',
    name: 'سواد نقي أموليد (AMOLED Black)',
    emoji: '🖤',
    description: 'سواد مطلق مع خطوط ناصعة وتباين فائق وتوفير للبطارية',
    textColor: '#F8FAFC',
    textMuted: '#94A3B8',
    cardBg: '#0B0B0C',
    surfaceBg: '#18181B',
    pageBg: '#000000',
    accentColor: '#38BDF8',
    borderColor: '#27272A',
    mode: 'dark',
  },
  {
    id: 'ultra-contrast-light',
    name: 'نهاري فائق الوضوح (Crisp Light)',
    emoji: '☀️',
    description: 'خط أسود فاحم عريض على بطاقات ومربعات بيضاء ناصعة',
    textColor: '#000000',
    textMuted: '#334155',
    cardBg: '#FFFFFF',
    surfaceBg: '#F1F5F9',
    pageBg: '#F8FAFC',
    accentColor: '#0284C7',
    borderColor: '#CBD5E1',
    mode: 'light',
  },
  {
    id: 'warm-paper-contrast',
    name: 'ورق قراءة دافئ مريح (Warm Paper)',
    emoji: '📜',
    description: 'ألوان حبر داكنة ومريحة للعين على أسطح عاجية واضحة',
    textColor: '#1C1917',
    textMuted: '#57534E',
    cardBg: '#FFFFFF',
    surfaceBg: '#F5EFE6',
    pageBg: '#FDFBF7',
    accentColor: '#D96B43',
    borderColor: '#D6D3D1',
    mode: 'light',
  },
];
